all: galactaIdle.o dededeIdle.o waddledeeIdle.o waddledooIdle.o knucklejoeIdle.o chefIdle.o bonkersIdle.o

galactaIdle.o: galactaIdle.c
	gcc -c -g galactaIdle.c

dededeIdle.o: dededeIdle.c
	gcc -c -g dededeIdle.c

waddledeeIdle.o: waddledeeIdle.c
	gcc -c -g waddledeeIdle.c

waddledooIdle.o: waddledooIdle.c
	gcc -c -g waddledooIdle.c

knucklejoeIdle.o: knucklejoeIdle.c
	gcc -c -g knucklejoeIdle.c

chefIdle.o: chefIdle.c
	gcc -c -g chefIdle.c

bonkersIdle.o: bonkersIdle.c
	gcc -c -g bonkersIdle.c
run:
	./program

clean:
	rm -f *.o *.gch
