all: galactaIdle.o dededeIdle.o waddledeeIdle.o waddledooIdle.o

galactaIdle.o: galactaIdle.c
	gcc -c -g galactaIdle.c

dededeIdle.o: dededeIdle.c
	gcc -c -g dededeIdle.c

waddledeeIdle.o: waddledeeIdle.c
	gcc -c -g waddledeeIdle.c

waddledooIdle.o: waddledooIdle.c
	gcc -c -g waddledooIdle.c

run:
	./program

clean:
	rm -f *.o *.gch
